### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by Hamid-Najafi** [flowcate/deephub-basic-setup#2]
It looks like deephub images are cross-coupled to X86 processors (is compiled for it, although it's not how docker works!), so it can't be deployed on ARM-based PC or SoCs

![Snag_1fefd1c](https://user-images.githubusercontent.com/17290304/212550549-d0d00960-96e7-417d-b41c-2e6718c5c410.png)

**Comment by benstadin** [comment]
DeepHub is a native application written in C++. We have no official support for ARM at the moment due to demand, though we have a beta version of the DeepHub backend available at flowcate/deephub-experimental:latest (at the time of writing this is 2.2.0-beta). 

The DeepHub UI image is currently not available for ARM, though it should be rather easy to build a Docker image for the UI's HTTP server, if required.

**Comment by wraromer** [comment]
The DeepHub is now officialy available for ARM as well. The docker images are in the official flowcate/deephub repository on docker.com: https://hub.docker.com/repository/docker/flowcate/deephub/general
